from typing import Optional, List, Dict
from uuid import UUID, uuid4
from datetime import datetime
from sqlmodel import SQLModel, Field, Relationship, Column
from pgvector.sqlalchemy import Vector
from sqlalchemy import JSON

class Meeting(SQLModel, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    title: str
    date: datetime = Field(default_factory=datetime.utcnow)
    source_filename: str
    file_type: str # 'vtt' or 'summary'
    status: str = Field(default="processing") # processing, completed, failed

    # Metadata extracted or aggregated
    summary_text: Optional[str] = None
    sentiment: Optional[str] = None

    # Google Calendar Integration
    google_event_id: Optional[str] = None

    chunks: List["TranscriptChunk"] = Relationship(back_populates="meeting")
    tasks: List["Task"] = Relationship(back_populates="meeting")

class TranscriptChunk(SQLModel, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    meeting_id: UUID = Field(foreign_key="meeting.id")

    start_time: float # seconds
    end_time: float # seconds
    speaker: str
    text: str

    # Embedding for RAG
    # 1536 is standard for OpenAI, but we can make it generic or dependent on model
    embedding: Optional[List[float]] = Field(default=None, sa_column=Column(Vector(1536)))

    # Clustering
    project_cluster_id: Optional[int] = None

    meeting: Meeting = Relationship(back_populates="chunks")

class Task(SQLModel, table=True):
    id: UUID = Field(default_factory=uuid4, primary_key=True)
    meeting_id: UUID = Field(foreign_key="meeting.id")

    description: str
    assignee: Optional[str] = None
    status: str = Field(default="todo") # todo, done
    due_date: Optional[datetime] = None

    meeting: Meeting = Relationship(back_populates="tasks")

class Project(SQLModel, table=True):
    """
    Represents a cluster of related meetings/chunks.
    Generated by the clustering algorithm.
    """
    id: int = Field(primary_key=True) # Cluster label from algorithm
    name: str # Generated by LLM
    centroid: List[float] = Field(sa_column=Column(Vector(1536)))
